/* SPDX-License-Identifier: GPL-2.0-only */

/*
 * SDXI MMIO register offsets and layouts.
 *
 * Copyright (C) 2025 Advanced Micro Devices, Inc.
 */

#ifndef DMA_SDXI_MMIO_H
#define DMA_SDXI_MMIO_H

#include <linux/bits.h>
#include <linux/compiler_attributes.h>
#include <linux/compiler_types.h>
#include <linux/types.h>

enum sdxi_reg {
	/* SDXI 1.0 9.1 General Control and Status Registers */
	SDXI_MMIO_CTL0       = 0x00000,
	SDXI_MMIO_CTL2       = 0x00010,
	SDXI_MMIO_STS0       = 0x00100,
	SDXI_MMIO_CAP0       = 0x00200,
	SDXI_MMIO_CAP1       = 0x00208,
	SDXI_MMIO_VERSION    = 0x00210,

	/* SDXI 1.0 9.2 Context and RKey Table Registers */
	SDXI_MMIO_CXT_L2     = 0x10000,
	SDXI_MMIO_RKEY       = 0x10100,

	/* SDXI 1.0 9.3 Error Logging Control and Status Registers */
	SDXI_MMIO_ERR_CTL    = 0x20000,
	SDXI_MMIO_ERR_STS    = 0x20008,
	SDXI_MMIO_ERR_CFG    = 0x20010,
	SDXI_MMIO_ERR_WRT    = 0x20020,
	SDXI_MMIO_ERR_RD     = 0x20028,
};

enum {
	/* SDXI 1.0 Table 9-2: MMIO_CTL0 */
	SDXI_MMIO_CTL0_FN_GSR         = GENMASK_ULL(1, 0),
	SDXI_MMIO_CTL0_FN_PASID_VL    = BIT_ULL(2),
	SDXI_MMIO_CTL0_FN_ERR_INTR_EN = BIT_ULL(4),
	SDXI_MMIO_CTL0_FN_PASID       = GENMASK_ULL(27, 8),
	SDXI_MMIO_CTL0_FN_GRP_ID      = GENMASK_ULL(63, 32),

	/* SDXI 1.0 Table 9-4: MMIO_CTL2 */
	SDXI_MMIO_CTL2_MAX_BUFFER  = GENMASK_ULL(3, 0),
	SDXI_MMIO_CTL2_MAX_AKEY_SZ = GENMASK_ULL(15, 12),
	SDXI_MMIO_CTL2_MAX_CXT     = GENMASK_ULL(31, 16),
	SDXI_MMIO_CTL2_OPB_000_AVL = GENMASK_ULL(63, 32),

	/* SDXI 1.0 Table 9-5: MMIO_STS0 */
	SDXI_MMIO_STS0_FN_GSV = GENMASK_ULL(2, 0),

	/* SDXI 1.0 Table 9-6: MMIO_CAP0 */
	SDXI_MMIO_CAP0_SFUNC          = GENMASK_ULL(15, 0),
	SDXI_MMIO_CAP0_DB_STRIDE      = GENMASK_ULL(22, 20),
	SDXI_MMIO_CAP0_MAX_DS_RING_SZ = GENMASK_ULL(28, 24),

	/* SDXI 1.0 Table 9-7: MMIO_CAP1 */
	SDXI_MMIO_CAP1_MAX_BUFFER    = GENMASK_ULL(3, 0),
	SDXI_MMIO_CAP1_RKEY_CAP      = BIT_ULL(4),
	SDXI_MMIO_CAP1_RM            = BIT_ULL(5),
	SDXI_MMIO_CAP1_MMIO64        = BIT_ULL(6),
	SDXI_MMIO_CAP1_MAX_ERRLOG_SZ = GENMASK_ULL(11, 8),
	SDXI_MMIO_CAP1_MAX_AKEY_SZ   = GENMASK_ULL(15, 12),
	SDXI_MMIO_CAP1_MAX_CXT       = GENMASK_ULL(31, 16),
	SDXI_MMIO_CAP1_OPB_000_CAP   = GENMASK_ULL(63, 32),

	/* SDXI 1.0 Table 9-8: MMIO_VERSION */
	SDXI_MMIO_VERSION_MINOR = GENMASK_ULL(7, 0),
	SDXI_MMIO_VERSION_MAJOR = GENMASK_ULL(23, 16),

	/* SDXI 1.0 Table 9-9: MMIO_CXT_L2 */
	SDXI_MMIO_CXT_L2_PTR = GENMASK_ULL(63, 12),

	/* SDXI 1.0 Table 9-10: MMIO_RKEY */
	SDXI_MMIO_RKEY_PTR = GENMASK_ULL(63, 12),
	SDXI_MMIO_RKEY_SZ  = GENMASK_ULL(4, 1),
	SDXI_MMIO_RKEY_EN  = BIT_ULL(0),

	/* SDXI 1.0 Table 9-11: MMIO_ERR_CTL */
	SDXI_MMIO_ERR_CTL_EN = BIT_ULL(0),

	/* SDXI 1.0 Table 9-12: MMIO_ERR_STS */
	SDXI_MMIO_ERR_STS_STS_BIT = BIT_ULL(0),
	SDXI_MMIO_ERR_STS_OVF_BIT = BIT_ULL(1),
	SDXI_MMIO_ERR_STS_ERR_BIT = BIT_ULL(3),

	/* SDXI 1.0 Table 9-13: MMIO_ERR_CFG */
	SDXI_MMIO_ERR_CFG_PTR = GENMASK_ULL(63, 12),
	SDXI_MMIO_ERR_CFG_SZ  = GENMASK_ULL(5, 1),
	SDXI_MMIO_ERR_CFG_EN  = BIT_ULL(0),
};

#endif  /* DMA_SDXI_MMIO_H */
